##        ░█████╗░███╗░░██╗████████╗██╗██████╗░██╗░░██╗░█████╗░░██████╗███████╗
##        ██╔══██╗████╗░██║╚══██╔══╝██║██╔══██╗██║░░██║██╔══██╗██╔════╝██╔════╝
##        ███████║██╔██╗██║░░░██║░░░██║██████╔╝███████║███████║╚█████╗░█████╗░░
##        ██╔══██║██║╚████║░░░██║░░░██║██╔═══╝░██╔══██║██╔══██║░╚═══██╗██╔══╝░░
##        ██║░░██║██║░╚███║░░░██║░░░██║██║░░░░░██║░░██║██║░░██║██████╔╝███████╗
##        ╚═╝░░╚═╝╚═╝░░╚══╝░░░╚═╝░░░╚═╝╚═╝░░░░░╚═╝░░╚═╝╚═╝░░╚═╝╚═════╝░╚══════╝

#Notify settings
# {PLAYER} - Player nickname
# {WHAT} - cheat level or type
notify:
  permission: "ac.notify"
  alert: "&bAntyCheat: &3{PLAYER} &fis suspected of: &3{WHAT}!"